/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as UsersauthRouteRouteImport } from './app/_usersauth/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as VendorsBillboardsRouteRouteImport } from './app/vendors/billboards/route'
import { Route as UsersauthUsersRouteRouteImport } from './app/_usersauth/users/route'
import { Route as UsersauthAdsRouteRouteImport } from './app/_usersauth/ads/route'
import { Route as PublicLightnavbarRouteRouteImport } from './app/_public/_lightnavbar/route'
import { Route as PublicDarknavbarRouteRouteImport } from './app/_public/_darknavbar/route'
import { Route as VendorsInfluencersIndexRouteImport } from './app/vendors/influencers/index'
import { Route as VendorsBillboardsIndexRouteImport } from './app/vendors/billboards/index'
import { Route as UsersauthUsersIndexRouteImport } from './app/_usersauth/users/index'
import { Route as UsersauthAdsIndexRouteImport } from './app/_usersauth/ads/index'
import { Route as AccessSignupIndexRouteImport } from './app/_access/signup/index'
import { Route as AccessSigninIndexRouteImport } from './app/_access/signin/index'
import { Route as AccessEmailVerificationIndexRouteImport } from './app/_access/email-verification/index'
import { Route as VendorsBillboardsWalletIndexRouteImport } from './app/vendors/billboards/wallet/index'
import { Route as VendorsBillboardsSettingsIndexRouteImport } from './app/vendors/billboards/settings/index'
import { Route as VendorsBillboardsRequestsIndexRouteImport } from './app/vendors/billboards/requests/index'
import { Route as VendorsBillboardsListingIndexRouteImport } from './app/vendors/billboards/listing/index'
import { Route as VendorsBillboardsAddBillboardIndexRouteImport } from './app/vendors/billboards/add-billboard/index'
import { Route as UsersauthUsersWalletIndexRouteImport } from './app/_usersauth/users/wallet/index'
import { Route as UsersauthUsersSettingsIndexRouteImport } from './app/_usersauth/users/settings/index'
import { Route as UsersauthUsersCampaignIndexRouteImport } from './app/_usersauth/users/campaign/index'
import { Route as UsersauthUsersAnalysisIndexRouteImport } from './app/_usersauth/users/analysis/index'
import { Route as UsersauthAdsWhatsappIndexRouteImport } from './app/_usersauth/ads/whatsapp/index'
import { Route as UsersauthAdsSmsIndexRouteImport } from './app/_usersauth/ads/sms/index'
import { Route as UsersauthAdsInfluencerIndexRouteImport } from './app/_usersauth/ads/influencer/index'
import { Route as UsersauthAdsDigitalIndexRouteImport } from './app/_usersauth/ads/digital/index'
import { Route as UsersauthAdsBillboardIndexRouteImport } from './app/_usersauth/ads/billboard/index'
import { Route as UsersauthAdsTransaction_idIndexRouteImport } from './app/_usersauth/ads/$transaction_id/index'
import { Route as PublicLightnavbarFaqsIndexRouteImport } from './app/_public/_lightnavbar/faqs/index'
import { Route as PublicLightnavbarContactIndexRouteImport } from './app/_public/_lightnavbar/contact/index'
import { Route as PublicLightnavbarAboutIndexRouteImport } from './app/_public/_lightnavbar/about/index'
import { Route as PublicDarknavbarDiscoveryIndexRouteImport } from './app/_public/_darknavbar/discovery/index'
import { Route as AccessVendorsAcessOnboardingIndexRouteImport } from './app/_access/vendors-acess/onboarding/index'
import { Route as AccessVendorsAcessLoginIndexRouteImport } from './app/_access/vendors-acess/login/index'
import { Route as VendorsBillboardsRequestsSlugIndexRouteImport } from './app/vendors/billboards/requests/$slug/index'
import { Route as VendorsBillboardsListingSlugIndexRouteImport } from './app/vendors/billboards/listing/$slug/index'
import { Route as UsersauthUsersWalletFundwalletIndexRouteImport } from './app/_usersauth/users/wallet/fundwallet/index'
import { Route as UsersauthUsersCampaignSlugIndexRouteImport } from './app/_usersauth/users/campaign/$slug/index'
import { Route as UsersauthAdsSmsCheckoutIndexRouteImport } from './app/_usersauth/ads/sms/checkout/index'
import { Route as UsersauthAdsInfluencerSlugIndexRouteImport } from './app/_usersauth/ads/influencer/$slug/index'
import { Route as UsersauthAdsBillboardSlugIndexRouteImport } from './app/_usersauth/ads/billboard/$slug/index'
import { Route as VendorsBillboardsListingSlugEditIndexRouteImport } from './app/vendors/billboards/listing/$slug/edit/index'
import { Route as UsersauthAdsInfluencerSlugOnboardingIndexRouteImport } from './app/_usersauth/ads/influencer/$slug/onboarding/index'
import { Route as UsersauthAdsBillboardSlugOnboardIndexRouteImport } from './app/_usersauth/ads/billboard/$slug/onboard/index'
import { Route as UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRouteImport } from './app/_usersauth/ads/influencer/$slug/onboarding/checkout/index'
import { Route as UsersauthAdsBillboardSlugOnboardCheckoutIndexRouteImport } from './app/_usersauth/ads/billboard/$slug/onboard/checkout/index'

const UsersauthRouteRoute = UsersauthRouteRouteImport.update({
  id: '/_usersauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsBillboardsRouteRoute = VendorsBillboardsRouteRouteImport.update({
  id: '/vendors/billboards',
  path: '/vendors/billboards',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersauthUsersRouteRoute = UsersauthUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => UsersauthRouteRoute,
} as any)
const UsersauthAdsRouteRoute = UsersauthAdsRouteRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => UsersauthRouteRoute,
} as any)
const PublicLightnavbarRouteRoute = PublicLightnavbarRouteRouteImport.update({
  id: '/_public/_lightnavbar',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDarknavbarRouteRoute = PublicDarknavbarRouteRouteImport.update({
  id: '/_public/_darknavbar',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsInfluencersIndexRoute = VendorsInfluencersIndexRouteImport.update({
  id: '/vendors/influencers/',
  path: '/vendors/influencers/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsBillboardsIndexRoute = VendorsBillboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsBillboardsRouteRoute,
} as any)
const UsersauthUsersIndexRoute = UsersauthUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersauthUsersRouteRoute,
} as any)
const UsersauthAdsIndexRoute = UsersauthAdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersauthAdsRouteRoute,
} as any)
const AccessSignupIndexRoute = AccessSignupIndexRouteImport.update({
  id: '/_access/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessSigninIndexRoute = AccessSigninIndexRouteImport.update({
  id: '/_access/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessEmailVerificationIndexRoute =
  AccessEmailVerificationIndexRouteImport.update({
    id: '/_access/email-verification/',
    path: '/email-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorsBillboardsWalletIndexRoute =
  VendorsBillboardsWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const VendorsBillboardsSettingsIndexRoute =
  VendorsBillboardsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const VendorsBillboardsRequestsIndexRoute =
  VendorsBillboardsRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const VendorsBillboardsListingIndexRoute =
  VendorsBillboardsListingIndexRouteImport.update({
    id: '/listing/',
    path: '/listing/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const VendorsBillboardsAddBillboardIndexRoute =
  VendorsBillboardsAddBillboardIndexRouteImport.update({
    id: '/add-billboard/',
    path: '/add-billboard/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const UsersauthUsersWalletIndexRoute =
  UsersauthUsersWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthUsersSettingsIndexRoute =
  UsersauthUsersSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthUsersCampaignIndexRoute =
  UsersauthUsersCampaignIndexRouteImport.update({
    id: '/campaign/',
    path: '/campaign/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthUsersAnalysisIndexRoute =
  UsersauthUsersAnalysisIndexRouteImport.update({
    id: '/analysis/',
    path: '/analysis/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthAdsWhatsappIndexRoute =
  UsersauthAdsWhatsappIndexRouteImport.update({
    id: '/whatsapp/',
    path: '/whatsapp/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsSmsIndexRoute = UsersauthAdsSmsIndexRouteImport.update({
  id: '/sms/',
  path: '/sms/',
  getParentRoute: () => UsersauthAdsRouteRoute,
} as any)
const UsersauthAdsInfluencerIndexRoute =
  UsersauthAdsInfluencerIndexRouteImport.update({
    id: '/influencer/',
    path: '/influencer/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsDigitalIndexRoute =
  UsersauthAdsDigitalIndexRouteImport.update({
    id: '/digital/',
    path: '/digital/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsBillboardIndexRoute =
  UsersauthAdsBillboardIndexRouteImport.update({
    id: '/billboard/',
    path: '/billboard/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsTransaction_idIndexRoute =
  UsersauthAdsTransaction_idIndexRouteImport.update({
    id: '/$transaction_id/',
    path: '/$transaction_id/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const PublicLightnavbarFaqsIndexRoute =
  PublicLightnavbarFaqsIndexRouteImport.update({
    id: '/faqs/',
    path: '/faqs/',
    getParentRoute: () => PublicLightnavbarRouteRoute,
  } as any)
const PublicLightnavbarContactIndexRoute =
  PublicLightnavbarContactIndexRouteImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => PublicLightnavbarRouteRoute,
  } as any)
const PublicLightnavbarAboutIndexRoute =
  PublicLightnavbarAboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => PublicLightnavbarRouteRoute,
  } as any)
const PublicDarknavbarDiscoveryIndexRoute =
  PublicDarknavbarDiscoveryIndexRouteImport.update({
    id: '/discovery/',
    path: '/discovery/',
    getParentRoute: () => PublicDarknavbarRouteRoute,
  } as any)
const AccessVendorsAcessOnboardingIndexRoute =
  AccessVendorsAcessOnboardingIndexRouteImport.update({
    id: '/_access/vendors-acess/onboarding/',
    path: '/vendors-acess/onboarding/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccessVendorsAcessLoginIndexRoute =
  AccessVendorsAcessLoginIndexRouteImport.update({
    id: '/_access/vendors-acess/login/',
    path: '/vendors-acess/login/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorsBillboardsRequestsSlugIndexRoute =
  VendorsBillboardsRequestsSlugIndexRouteImport.update({
    id: '/requests/$slug/',
    path: '/requests/$slug/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const VendorsBillboardsListingSlugIndexRoute =
  VendorsBillboardsListingSlugIndexRouteImport.update({
    id: '/listing/$slug/',
    path: '/listing/$slug/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const UsersauthUsersWalletFundwalletIndexRoute =
  UsersauthUsersWalletFundwalletIndexRouteImport.update({
    id: '/wallet/fundwallet/',
    path: '/wallet/fundwallet/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthUsersCampaignSlugIndexRoute =
  UsersauthUsersCampaignSlugIndexRouteImport.update({
    id: '/campaign/$slug/',
    path: '/campaign/$slug/',
    getParentRoute: () => UsersauthUsersRouteRoute,
  } as any)
const UsersauthAdsSmsCheckoutIndexRoute =
  UsersauthAdsSmsCheckoutIndexRouteImport.update({
    id: '/sms/checkout/',
    path: '/sms/checkout/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsInfluencerSlugIndexRoute =
  UsersauthAdsInfluencerSlugIndexRouteImport.update({
    id: '/influencer/$slug/',
    path: '/influencer/$slug/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsBillboardSlugIndexRoute =
  UsersauthAdsBillboardSlugIndexRouteImport.update({
    id: '/billboard/$slug/',
    path: '/billboard/$slug/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const VendorsBillboardsListingSlugEditIndexRoute =
  VendorsBillboardsListingSlugEditIndexRouteImport.update({
    id: '/listing/$slug/edit/',
    path: '/listing/$slug/edit/',
    getParentRoute: () => VendorsBillboardsRouteRoute,
  } as any)
const UsersauthAdsInfluencerSlugOnboardingIndexRoute =
  UsersauthAdsInfluencerSlugOnboardingIndexRouteImport.update({
    id: '/influencer/$slug/onboarding/',
    path: '/influencer/$slug/onboarding/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsBillboardSlugOnboardIndexRoute =
  UsersauthAdsBillboardSlugOnboardIndexRouteImport.update({
    id: '/billboard/$slug/onboard/',
    path: '/billboard/$slug/onboard/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute =
  UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRouteImport.update({
    id: '/influencer/$slug/onboarding/checkout/',
    path: '/influencer/$slug/onboarding/checkout/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)
const UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute =
  UsersauthAdsBillboardSlugOnboardCheckoutIndexRouteImport.update({
    id: '/billboard/$slug/onboard/checkout/',
    path: '/billboard/$slug/onboard/checkout/',
    getParentRoute: () => UsersauthAdsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof UsersauthAdsRouteRouteWithChildren
  '/users': typeof UsersauthUsersRouteRouteWithChildren
  '/vendors/billboards': typeof VendorsBillboardsRouteRouteWithChildren
  '/email-verification/': typeof AccessEmailVerificationIndexRoute
  '/signin/': typeof AccessSigninIndexRoute
  '/signup/': typeof AccessSignupIndexRoute
  '/ads/': typeof UsersauthAdsIndexRoute
  '/users/': typeof UsersauthUsersIndexRoute
  '/vendors/billboards/': typeof VendorsBillboardsIndexRoute
  '/vendors/influencers/': typeof VendorsInfluencersIndexRoute
  '/vendors-acess/login/': typeof AccessVendorsAcessLoginIndexRoute
  '/vendors-acess/onboarding/': typeof AccessVendorsAcessOnboardingIndexRoute
  '/discovery/': typeof PublicDarknavbarDiscoveryIndexRoute
  '/about/': typeof PublicLightnavbarAboutIndexRoute
  '/contact/': typeof PublicLightnavbarContactIndexRoute
  '/faqs/': typeof PublicLightnavbarFaqsIndexRoute
  '/ads/$transaction_id/': typeof UsersauthAdsTransaction_idIndexRoute
  '/ads/billboard/': typeof UsersauthAdsBillboardIndexRoute
  '/ads/digital/': typeof UsersauthAdsDigitalIndexRoute
  '/ads/influencer/': typeof UsersauthAdsInfluencerIndexRoute
  '/ads/sms/': typeof UsersauthAdsSmsIndexRoute
  '/ads/whatsapp/': typeof UsersauthAdsWhatsappIndexRoute
  '/users/analysis/': typeof UsersauthUsersAnalysisIndexRoute
  '/users/campaign/': typeof UsersauthUsersCampaignIndexRoute
  '/users/settings/': typeof UsersauthUsersSettingsIndexRoute
  '/users/wallet/': typeof UsersauthUsersWalletIndexRoute
  '/vendors/billboards/add-billboard/': typeof VendorsBillboardsAddBillboardIndexRoute
  '/vendors/billboards/listing/': typeof VendorsBillboardsListingIndexRoute
  '/vendors/billboards/requests/': typeof VendorsBillboardsRequestsIndexRoute
  '/vendors/billboards/settings/': typeof VendorsBillboardsSettingsIndexRoute
  '/vendors/billboards/wallet/': typeof VendorsBillboardsWalletIndexRoute
  '/ads/billboard/$slug/': typeof UsersauthAdsBillboardSlugIndexRoute
  '/ads/influencer/$slug/': typeof UsersauthAdsInfluencerSlugIndexRoute
  '/ads/sms/checkout/': typeof UsersauthAdsSmsCheckoutIndexRoute
  '/users/campaign/$slug/': typeof UsersauthUsersCampaignSlugIndexRoute
  '/users/wallet/fundwallet/': typeof UsersauthUsersWalletFundwalletIndexRoute
  '/vendors/billboards/listing/$slug/': typeof VendorsBillboardsListingSlugIndexRoute
  '/vendors/billboards/requests/$slug/': typeof VendorsBillboardsRequestsSlugIndexRoute
  '/ads/billboard/$slug/onboard/': typeof UsersauthAdsBillboardSlugOnboardIndexRoute
  '/ads/influencer/$slug/onboarding/': typeof UsersauthAdsInfluencerSlugOnboardingIndexRoute
  '/vendors/billboards/listing/$slug/edit/': typeof VendorsBillboardsListingSlugEditIndexRoute
  '/ads/billboard/$slug/onboard/checkout/': typeof UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute
  '/ads/influencer/$slug/onboarding/checkout/': typeof UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-verification': typeof AccessEmailVerificationIndexRoute
  '/signin': typeof AccessSigninIndexRoute
  '/signup': typeof AccessSignupIndexRoute
  '/ads': typeof UsersauthAdsIndexRoute
  '/users': typeof UsersauthUsersIndexRoute
  '/vendors/billboards': typeof VendorsBillboardsIndexRoute
  '/vendors/influencers': typeof VendorsInfluencersIndexRoute
  '/vendors-acess/login': typeof AccessVendorsAcessLoginIndexRoute
  '/vendors-acess/onboarding': typeof AccessVendorsAcessOnboardingIndexRoute
  '/discovery': typeof PublicDarknavbarDiscoveryIndexRoute
  '/about': typeof PublicLightnavbarAboutIndexRoute
  '/contact': typeof PublicLightnavbarContactIndexRoute
  '/faqs': typeof PublicLightnavbarFaqsIndexRoute
  '/ads/$transaction_id': typeof UsersauthAdsTransaction_idIndexRoute
  '/ads/billboard': typeof UsersauthAdsBillboardIndexRoute
  '/ads/digital': typeof UsersauthAdsDigitalIndexRoute
  '/ads/influencer': typeof UsersauthAdsInfluencerIndexRoute
  '/ads/sms': typeof UsersauthAdsSmsIndexRoute
  '/ads/whatsapp': typeof UsersauthAdsWhatsappIndexRoute
  '/users/analysis': typeof UsersauthUsersAnalysisIndexRoute
  '/users/campaign': typeof UsersauthUsersCampaignIndexRoute
  '/users/settings': typeof UsersauthUsersSettingsIndexRoute
  '/users/wallet': typeof UsersauthUsersWalletIndexRoute
  '/vendors/billboards/add-billboard': typeof VendorsBillboardsAddBillboardIndexRoute
  '/vendors/billboards/listing': typeof VendorsBillboardsListingIndexRoute
  '/vendors/billboards/requests': typeof VendorsBillboardsRequestsIndexRoute
  '/vendors/billboards/settings': typeof VendorsBillboardsSettingsIndexRoute
  '/vendors/billboards/wallet': typeof VendorsBillboardsWalletIndexRoute
  '/ads/billboard/$slug': typeof UsersauthAdsBillboardSlugIndexRoute
  '/ads/influencer/$slug': typeof UsersauthAdsInfluencerSlugIndexRoute
  '/ads/sms/checkout': typeof UsersauthAdsSmsCheckoutIndexRoute
  '/users/campaign/$slug': typeof UsersauthUsersCampaignSlugIndexRoute
  '/users/wallet/fundwallet': typeof UsersauthUsersWalletFundwalletIndexRoute
  '/vendors/billboards/listing/$slug': typeof VendorsBillboardsListingSlugIndexRoute
  '/vendors/billboards/requests/$slug': typeof VendorsBillboardsRequestsSlugIndexRoute
  '/ads/billboard/$slug/onboard': typeof UsersauthAdsBillboardSlugOnboardIndexRoute
  '/ads/influencer/$slug/onboarding': typeof UsersauthAdsInfluencerSlugOnboardingIndexRoute
  '/vendors/billboards/listing/$slug/edit': typeof VendorsBillboardsListingSlugEditIndexRoute
  '/ads/billboard/$slug/onboard/checkout': typeof UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute
  '/ads/influencer/$slug/onboarding/checkout': typeof UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_usersauth': typeof UsersauthRouteRouteWithChildren
  '/_public/_darknavbar': typeof PublicDarknavbarRouteRouteWithChildren
  '/_public/_lightnavbar': typeof PublicLightnavbarRouteRouteWithChildren
  '/_usersauth/ads': typeof UsersauthAdsRouteRouteWithChildren
  '/_usersauth/users': typeof UsersauthUsersRouteRouteWithChildren
  '/vendors/billboards': typeof VendorsBillboardsRouteRouteWithChildren
  '/_access/email-verification/': typeof AccessEmailVerificationIndexRoute
  '/_access/signin/': typeof AccessSigninIndexRoute
  '/_access/signup/': typeof AccessSignupIndexRoute
  '/_usersauth/ads/': typeof UsersauthAdsIndexRoute
  '/_usersauth/users/': typeof UsersauthUsersIndexRoute
  '/vendors/billboards/': typeof VendorsBillboardsIndexRoute
  '/vendors/influencers/': typeof VendorsInfluencersIndexRoute
  '/_access/vendors-acess/login/': typeof AccessVendorsAcessLoginIndexRoute
  '/_access/vendors-acess/onboarding/': typeof AccessVendorsAcessOnboardingIndexRoute
  '/_public/_darknavbar/discovery/': typeof PublicDarknavbarDiscoveryIndexRoute
  '/_public/_lightnavbar/about/': typeof PublicLightnavbarAboutIndexRoute
  '/_public/_lightnavbar/contact/': typeof PublicLightnavbarContactIndexRoute
  '/_public/_lightnavbar/faqs/': typeof PublicLightnavbarFaqsIndexRoute
  '/_usersauth/ads/$transaction_id/': typeof UsersauthAdsTransaction_idIndexRoute
  '/_usersauth/ads/billboard/': typeof UsersauthAdsBillboardIndexRoute
  '/_usersauth/ads/digital/': typeof UsersauthAdsDigitalIndexRoute
  '/_usersauth/ads/influencer/': typeof UsersauthAdsInfluencerIndexRoute
  '/_usersauth/ads/sms/': typeof UsersauthAdsSmsIndexRoute
  '/_usersauth/ads/whatsapp/': typeof UsersauthAdsWhatsappIndexRoute
  '/_usersauth/users/analysis/': typeof UsersauthUsersAnalysisIndexRoute
  '/_usersauth/users/campaign/': typeof UsersauthUsersCampaignIndexRoute
  '/_usersauth/users/settings/': typeof UsersauthUsersSettingsIndexRoute
  '/_usersauth/users/wallet/': typeof UsersauthUsersWalletIndexRoute
  '/vendors/billboards/add-billboard/': typeof VendorsBillboardsAddBillboardIndexRoute
  '/vendors/billboards/listing/': typeof VendorsBillboardsListingIndexRoute
  '/vendors/billboards/requests/': typeof VendorsBillboardsRequestsIndexRoute
  '/vendors/billboards/settings/': typeof VendorsBillboardsSettingsIndexRoute
  '/vendors/billboards/wallet/': typeof VendorsBillboardsWalletIndexRoute
  '/_usersauth/ads/billboard/$slug/': typeof UsersauthAdsBillboardSlugIndexRoute
  '/_usersauth/ads/influencer/$slug/': typeof UsersauthAdsInfluencerSlugIndexRoute
  '/_usersauth/ads/sms/checkout/': typeof UsersauthAdsSmsCheckoutIndexRoute
  '/_usersauth/users/campaign/$slug/': typeof UsersauthUsersCampaignSlugIndexRoute
  '/_usersauth/users/wallet/fundwallet/': typeof UsersauthUsersWalletFundwalletIndexRoute
  '/vendors/billboards/listing/$slug/': typeof VendorsBillboardsListingSlugIndexRoute
  '/vendors/billboards/requests/$slug/': typeof VendorsBillboardsRequestsSlugIndexRoute
  '/_usersauth/ads/billboard/$slug/onboard/': typeof UsersauthAdsBillboardSlugOnboardIndexRoute
  '/_usersauth/ads/influencer/$slug/onboarding/': typeof UsersauthAdsInfluencerSlugOnboardingIndexRoute
  '/vendors/billboards/listing/$slug/edit/': typeof VendorsBillboardsListingSlugEditIndexRoute
  '/_usersauth/ads/billboard/$slug/onboard/checkout/': typeof UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute
  '/_usersauth/ads/influencer/$slug/onboarding/checkout/': typeof UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/users'
    | '/vendors/billboards'
    | '/email-verification/'
    | '/signin/'
    | '/signup/'
    | '/ads/'
    | '/users/'
    | '/vendors/billboards/'
    | '/vendors/influencers/'
    | '/vendors-acess/login/'
    | '/vendors-acess/onboarding/'
    | '/discovery/'
    | '/about/'
    | '/contact/'
    | '/faqs/'
    | '/ads/$transaction_id/'
    | '/ads/billboard/'
    | '/ads/digital/'
    | '/ads/influencer/'
    | '/ads/sms/'
    | '/ads/whatsapp/'
    | '/users/analysis/'
    | '/users/campaign/'
    | '/users/settings/'
    | '/users/wallet/'
    | '/vendors/billboards/add-billboard/'
    | '/vendors/billboards/listing/'
    | '/vendors/billboards/requests/'
    | '/vendors/billboards/settings/'
    | '/vendors/billboards/wallet/'
    | '/ads/billboard/$slug/'
    | '/ads/influencer/$slug/'
    | '/ads/sms/checkout/'
    | '/users/campaign/$slug/'
    | '/users/wallet/fundwallet/'
    | '/vendors/billboards/listing/$slug/'
    | '/vendors/billboards/requests/$slug/'
    | '/ads/billboard/$slug/onboard/'
    | '/ads/influencer/$slug/onboarding/'
    | '/vendors/billboards/listing/$slug/edit/'
    | '/ads/billboard/$slug/onboard/checkout/'
    | '/ads/influencer/$slug/onboarding/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-verification'
    | '/signin'
    | '/signup'
    | '/ads'
    | '/users'
    | '/vendors/billboards'
    | '/vendors/influencers'
    | '/vendors-acess/login'
    | '/vendors-acess/onboarding'
    | '/discovery'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/ads/$transaction_id'
    | '/ads/billboard'
    | '/ads/digital'
    | '/ads/influencer'
    | '/ads/sms'
    | '/ads/whatsapp'
    | '/users/analysis'
    | '/users/campaign'
    | '/users/settings'
    | '/users/wallet'
    | '/vendors/billboards/add-billboard'
    | '/vendors/billboards/listing'
    | '/vendors/billboards/requests'
    | '/vendors/billboards/settings'
    | '/vendors/billboards/wallet'
    | '/ads/billboard/$slug'
    | '/ads/influencer/$slug'
    | '/ads/sms/checkout'
    | '/users/campaign/$slug'
    | '/users/wallet/fundwallet'
    | '/vendors/billboards/listing/$slug'
    | '/vendors/billboards/requests/$slug'
    | '/ads/billboard/$slug/onboard'
    | '/ads/influencer/$slug/onboarding'
    | '/vendors/billboards/listing/$slug/edit'
    | '/ads/billboard/$slug/onboard/checkout'
    | '/ads/influencer/$slug/onboarding/checkout'
  id:
    | '__root__'
    | '/'
    | '/_usersauth'
    | '/_public/_darknavbar'
    | '/_public/_lightnavbar'
    | '/_usersauth/ads'
    | '/_usersauth/users'
    | '/vendors/billboards'
    | '/_access/email-verification/'
    | '/_access/signin/'
    | '/_access/signup/'
    | '/_usersauth/ads/'
    | '/_usersauth/users/'
    | '/vendors/billboards/'
    | '/vendors/influencers/'
    | '/_access/vendors-acess/login/'
    | '/_access/vendors-acess/onboarding/'
    | '/_public/_darknavbar/discovery/'
    | '/_public/_lightnavbar/about/'
    | '/_public/_lightnavbar/contact/'
    | '/_public/_lightnavbar/faqs/'
    | '/_usersauth/ads/$transaction_id/'
    | '/_usersauth/ads/billboard/'
    | '/_usersauth/ads/digital/'
    | '/_usersauth/ads/influencer/'
    | '/_usersauth/ads/sms/'
    | '/_usersauth/ads/whatsapp/'
    | '/_usersauth/users/analysis/'
    | '/_usersauth/users/campaign/'
    | '/_usersauth/users/settings/'
    | '/_usersauth/users/wallet/'
    | '/vendors/billboards/add-billboard/'
    | '/vendors/billboards/listing/'
    | '/vendors/billboards/requests/'
    | '/vendors/billboards/settings/'
    | '/vendors/billboards/wallet/'
    | '/_usersauth/ads/billboard/$slug/'
    | '/_usersauth/ads/influencer/$slug/'
    | '/_usersauth/ads/sms/checkout/'
    | '/_usersauth/users/campaign/$slug/'
    | '/_usersauth/users/wallet/fundwallet/'
    | '/vendors/billboards/listing/$slug/'
    | '/vendors/billboards/requests/$slug/'
    | '/_usersauth/ads/billboard/$slug/onboard/'
    | '/_usersauth/ads/influencer/$slug/onboarding/'
    | '/vendors/billboards/listing/$slug/edit/'
    | '/_usersauth/ads/billboard/$slug/onboard/checkout/'
    | '/_usersauth/ads/influencer/$slug/onboarding/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersauthRouteRoute: typeof UsersauthRouteRouteWithChildren
  PublicDarknavbarRouteRoute: typeof PublicDarknavbarRouteRouteWithChildren
  PublicLightnavbarRouteRoute: typeof PublicLightnavbarRouteRouteWithChildren
  VendorsBillboardsRouteRoute: typeof VendorsBillboardsRouteRouteWithChildren
  AccessEmailVerificationIndexRoute: typeof AccessEmailVerificationIndexRoute
  AccessSigninIndexRoute: typeof AccessSigninIndexRoute
  AccessSignupIndexRoute: typeof AccessSignupIndexRoute
  VendorsInfluencersIndexRoute: typeof VendorsInfluencersIndexRoute
  AccessVendorsAcessLoginIndexRoute: typeof AccessVendorsAcessLoginIndexRoute
  AccessVendorsAcessOnboardingIndexRoute: typeof AccessVendorsAcessOnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_usersauth': {
      id: '/_usersauth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UsersauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/billboards': {
      id: '/vendors/billboards'
      path: '/vendors/billboards'
      fullPath: '/vendors/billboards'
      preLoaderRoute: typeof VendorsBillboardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_usersauth/users': {
      id: '/_usersauth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersauthUsersRouteRouteImport
      parentRoute: typeof UsersauthRouteRoute
    }
    '/_usersauth/ads': {
      id: '/_usersauth/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof UsersauthAdsRouteRouteImport
      parentRoute: typeof UsersauthRouteRoute
    }
    '/_public/_lightnavbar': {
      id: '/_public/_lightnavbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLightnavbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_darknavbar': {
      id: '/_public/_darknavbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicDarknavbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/influencers/': {
      id: '/vendors/influencers/'
      path: '/vendors/influencers'
      fullPath: '/vendors/influencers/'
      preLoaderRoute: typeof VendorsInfluencersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/billboards/': {
      id: '/vendors/billboards/'
      path: '/'
      fullPath: '/vendors/billboards/'
      preLoaderRoute: typeof VendorsBillboardsIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/_usersauth/users/': {
      id: '/_usersauth/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersauthUsersIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/ads/': {
      id: '/_usersauth/ads/'
      path: '/'
      fullPath: '/ads/'
      preLoaderRoute: typeof UsersauthAdsIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_access/signup/': {
      id: '/_access/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AccessSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_access/signin/': {
      id: '/_access/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof AccessSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_access/email-verification/': {
      id: '/_access/email-verification/'
      path: '/email-verification'
      fullPath: '/email-verification/'
      preLoaderRoute: typeof AccessEmailVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/billboards/wallet/': {
      id: '/vendors/billboards/wallet/'
      path: '/wallet'
      fullPath: '/vendors/billboards/wallet/'
      preLoaderRoute: typeof VendorsBillboardsWalletIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/vendors/billboards/settings/': {
      id: '/vendors/billboards/settings/'
      path: '/settings'
      fullPath: '/vendors/billboards/settings/'
      preLoaderRoute: typeof VendorsBillboardsSettingsIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/vendors/billboards/requests/': {
      id: '/vendors/billboards/requests/'
      path: '/requests'
      fullPath: '/vendors/billboards/requests/'
      preLoaderRoute: typeof VendorsBillboardsRequestsIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/vendors/billboards/listing/': {
      id: '/vendors/billboards/listing/'
      path: '/listing'
      fullPath: '/vendors/billboards/listing/'
      preLoaderRoute: typeof VendorsBillboardsListingIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/vendors/billboards/add-billboard/': {
      id: '/vendors/billboards/add-billboard/'
      path: '/add-billboard'
      fullPath: '/vendors/billboards/add-billboard/'
      preLoaderRoute: typeof VendorsBillboardsAddBillboardIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/_usersauth/users/wallet/': {
      id: '/_usersauth/users/wallet/'
      path: '/wallet'
      fullPath: '/users/wallet/'
      preLoaderRoute: typeof UsersauthUsersWalletIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/users/settings/': {
      id: '/_usersauth/users/settings/'
      path: '/settings'
      fullPath: '/users/settings/'
      preLoaderRoute: typeof UsersauthUsersSettingsIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/users/campaign/': {
      id: '/_usersauth/users/campaign/'
      path: '/campaign'
      fullPath: '/users/campaign/'
      preLoaderRoute: typeof UsersauthUsersCampaignIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/users/analysis/': {
      id: '/_usersauth/users/analysis/'
      path: '/analysis'
      fullPath: '/users/analysis/'
      preLoaderRoute: typeof UsersauthUsersAnalysisIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/ads/whatsapp/': {
      id: '/_usersauth/ads/whatsapp/'
      path: '/whatsapp'
      fullPath: '/ads/whatsapp/'
      preLoaderRoute: typeof UsersauthAdsWhatsappIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/sms/': {
      id: '/_usersauth/ads/sms/'
      path: '/sms'
      fullPath: '/ads/sms/'
      preLoaderRoute: typeof UsersauthAdsSmsIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/influencer/': {
      id: '/_usersauth/ads/influencer/'
      path: '/influencer'
      fullPath: '/ads/influencer/'
      preLoaderRoute: typeof UsersauthAdsInfluencerIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/digital/': {
      id: '/_usersauth/ads/digital/'
      path: '/digital'
      fullPath: '/ads/digital/'
      preLoaderRoute: typeof UsersauthAdsDigitalIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/billboard/': {
      id: '/_usersauth/ads/billboard/'
      path: '/billboard'
      fullPath: '/ads/billboard/'
      preLoaderRoute: typeof UsersauthAdsBillboardIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/$transaction_id/': {
      id: '/_usersauth/ads/$transaction_id/'
      path: '/$transaction_id'
      fullPath: '/ads/$transaction_id/'
      preLoaderRoute: typeof UsersauthAdsTransaction_idIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_public/_lightnavbar/faqs/': {
      id: '/_public/_lightnavbar/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof PublicLightnavbarFaqsIndexRouteImport
      parentRoute: typeof PublicLightnavbarRouteRoute
    }
    '/_public/_lightnavbar/contact/': {
      id: '/_public/_lightnavbar/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof PublicLightnavbarContactIndexRouteImport
      parentRoute: typeof PublicLightnavbarRouteRoute
    }
    '/_public/_lightnavbar/about/': {
      id: '/_public/_lightnavbar/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicLightnavbarAboutIndexRouteImport
      parentRoute: typeof PublicLightnavbarRouteRoute
    }
    '/_public/_darknavbar/discovery/': {
      id: '/_public/_darknavbar/discovery/'
      path: '/discovery'
      fullPath: '/discovery/'
      preLoaderRoute: typeof PublicDarknavbarDiscoveryIndexRouteImport
      parentRoute: typeof PublicDarknavbarRouteRoute
    }
    '/_access/vendors-acess/onboarding/': {
      id: '/_access/vendors-acess/onboarding/'
      path: '/vendors-acess/onboarding'
      fullPath: '/vendors-acess/onboarding/'
      preLoaderRoute: typeof AccessVendorsAcessOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_access/vendors-acess/login/': {
      id: '/_access/vendors-acess/login/'
      path: '/vendors-acess/login'
      fullPath: '/vendors-acess/login/'
      preLoaderRoute: typeof AccessVendorsAcessLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/billboards/requests/$slug/': {
      id: '/vendors/billboards/requests/$slug/'
      path: '/requests/$slug'
      fullPath: '/vendors/billboards/requests/$slug/'
      preLoaderRoute: typeof VendorsBillboardsRequestsSlugIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/vendors/billboards/listing/$slug/': {
      id: '/vendors/billboards/listing/$slug/'
      path: '/listing/$slug'
      fullPath: '/vendors/billboards/listing/$slug/'
      preLoaderRoute: typeof VendorsBillboardsListingSlugIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/_usersauth/users/wallet/fundwallet/': {
      id: '/_usersauth/users/wallet/fundwallet/'
      path: '/wallet/fundwallet'
      fullPath: '/users/wallet/fundwallet/'
      preLoaderRoute: typeof UsersauthUsersWalletFundwalletIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/users/campaign/$slug/': {
      id: '/_usersauth/users/campaign/$slug/'
      path: '/campaign/$slug'
      fullPath: '/users/campaign/$slug/'
      preLoaderRoute: typeof UsersauthUsersCampaignSlugIndexRouteImport
      parentRoute: typeof UsersauthUsersRouteRoute
    }
    '/_usersauth/ads/sms/checkout/': {
      id: '/_usersauth/ads/sms/checkout/'
      path: '/sms/checkout'
      fullPath: '/ads/sms/checkout/'
      preLoaderRoute: typeof UsersauthAdsSmsCheckoutIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/influencer/$slug/': {
      id: '/_usersauth/ads/influencer/$slug/'
      path: '/influencer/$slug'
      fullPath: '/ads/influencer/$slug/'
      preLoaderRoute: typeof UsersauthAdsInfluencerSlugIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/billboard/$slug/': {
      id: '/_usersauth/ads/billboard/$slug/'
      path: '/billboard/$slug'
      fullPath: '/ads/billboard/$slug/'
      preLoaderRoute: typeof UsersauthAdsBillboardSlugIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/vendors/billboards/listing/$slug/edit/': {
      id: '/vendors/billboards/listing/$slug/edit/'
      path: '/listing/$slug/edit'
      fullPath: '/vendors/billboards/listing/$slug/edit/'
      preLoaderRoute: typeof VendorsBillboardsListingSlugEditIndexRouteImport
      parentRoute: typeof VendorsBillboardsRouteRoute
    }
    '/_usersauth/ads/influencer/$slug/onboarding/': {
      id: '/_usersauth/ads/influencer/$slug/onboarding/'
      path: '/influencer/$slug/onboarding'
      fullPath: '/ads/influencer/$slug/onboarding/'
      preLoaderRoute: typeof UsersauthAdsInfluencerSlugOnboardingIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/billboard/$slug/onboard/': {
      id: '/_usersauth/ads/billboard/$slug/onboard/'
      path: '/billboard/$slug/onboard'
      fullPath: '/ads/billboard/$slug/onboard/'
      preLoaderRoute: typeof UsersauthAdsBillboardSlugOnboardIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/influencer/$slug/onboarding/checkout/': {
      id: '/_usersauth/ads/influencer/$slug/onboarding/checkout/'
      path: '/influencer/$slug/onboarding/checkout'
      fullPath: '/ads/influencer/$slug/onboarding/checkout/'
      preLoaderRoute: typeof UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
    '/_usersauth/ads/billboard/$slug/onboard/checkout/': {
      id: '/_usersauth/ads/billboard/$slug/onboard/checkout/'
      path: '/billboard/$slug/onboard/checkout'
      fullPath: '/ads/billboard/$slug/onboard/checkout/'
      preLoaderRoute: typeof UsersauthAdsBillboardSlugOnboardCheckoutIndexRouteImport
      parentRoute: typeof UsersauthAdsRouteRoute
    }
  }
}

interface UsersauthAdsRouteRouteChildren {
  UsersauthAdsIndexRoute: typeof UsersauthAdsIndexRoute
  UsersauthAdsTransaction_idIndexRoute: typeof UsersauthAdsTransaction_idIndexRoute
  UsersauthAdsBillboardIndexRoute: typeof UsersauthAdsBillboardIndexRoute
  UsersauthAdsDigitalIndexRoute: typeof UsersauthAdsDigitalIndexRoute
  UsersauthAdsInfluencerIndexRoute: typeof UsersauthAdsInfluencerIndexRoute
  UsersauthAdsSmsIndexRoute: typeof UsersauthAdsSmsIndexRoute
  UsersauthAdsWhatsappIndexRoute: typeof UsersauthAdsWhatsappIndexRoute
  UsersauthAdsBillboardSlugIndexRoute: typeof UsersauthAdsBillboardSlugIndexRoute
  UsersauthAdsInfluencerSlugIndexRoute: typeof UsersauthAdsInfluencerSlugIndexRoute
  UsersauthAdsSmsCheckoutIndexRoute: typeof UsersauthAdsSmsCheckoutIndexRoute
  UsersauthAdsBillboardSlugOnboardIndexRoute: typeof UsersauthAdsBillboardSlugOnboardIndexRoute
  UsersauthAdsInfluencerSlugOnboardingIndexRoute: typeof UsersauthAdsInfluencerSlugOnboardingIndexRoute
  UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute: typeof UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute
  UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute: typeof UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute
}

const UsersauthAdsRouteRouteChildren: UsersauthAdsRouteRouteChildren = {
  UsersauthAdsIndexRoute: UsersauthAdsIndexRoute,
  UsersauthAdsTransaction_idIndexRoute: UsersauthAdsTransaction_idIndexRoute,
  UsersauthAdsBillboardIndexRoute: UsersauthAdsBillboardIndexRoute,
  UsersauthAdsDigitalIndexRoute: UsersauthAdsDigitalIndexRoute,
  UsersauthAdsInfluencerIndexRoute: UsersauthAdsInfluencerIndexRoute,
  UsersauthAdsSmsIndexRoute: UsersauthAdsSmsIndexRoute,
  UsersauthAdsWhatsappIndexRoute: UsersauthAdsWhatsappIndexRoute,
  UsersauthAdsBillboardSlugIndexRoute: UsersauthAdsBillboardSlugIndexRoute,
  UsersauthAdsInfluencerSlugIndexRoute: UsersauthAdsInfluencerSlugIndexRoute,
  UsersauthAdsSmsCheckoutIndexRoute: UsersauthAdsSmsCheckoutIndexRoute,
  UsersauthAdsBillboardSlugOnboardIndexRoute:
    UsersauthAdsBillboardSlugOnboardIndexRoute,
  UsersauthAdsInfluencerSlugOnboardingIndexRoute:
    UsersauthAdsInfluencerSlugOnboardingIndexRoute,
  UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute:
    UsersauthAdsBillboardSlugOnboardCheckoutIndexRoute,
  UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute:
    UsersauthAdsInfluencerSlugOnboardingCheckoutIndexRoute,
}

const UsersauthAdsRouteRouteWithChildren =
  UsersauthAdsRouteRoute._addFileChildren(UsersauthAdsRouteRouteChildren)

interface UsersauthUsersRouteRouteChildren {
  UsersauthUsersIndexRoute: typeof UsersauthUsersIndexRoute
  UsersauthUsersAnalysisIndexRoute: typeof UsersauthUsersAnalysisIndexRoute
  UsersauthUsersCampaignIndexRoute: typeof UsersauthUsersCampaignIndexRoute
  UsersauthUsersSettingsIndexRoute: typeof UsersauthUsersSettingsIndexRoute
  UsersauthUsersWalletIndexRoute: typeof UsersauthUsersWalletIndexRoute
  UsersauthUsersCampaignSlugIndexRoute: typeof UsersauthUsersCampaignSlugIndexRoute
  UsersauthUsersWalletFundwalletIndexRoute: typeof UsersauthUsersWalletFundwalletIndexRoute
}

const UsersauthUsersRouteRouteChildren: UsersauthUsersRouteRouteChildren = {
  UsersauthUsersIndexRoute: UsersauthUsersIndexRoute,
  UsersauthUsersAnalysisIndexRoute: UsersauthUsersAnalysisIndexRoute,
  UsersauthUsersCampaignIndexRoute: UsersauthUsersCampaignIndexRoute,
  UsersauthUsersSettingsIndexRoute: UsersauthUsersSettingsIndexRoute,
  UsersauthUsersWalletIndexRoute: UsersauthUsersWalletIndexRoute,
  UsersauthUsersCampaignSlugIndexRoute: UsersauthUsersCampaignSlugIndexRoute,
  UsersauthUsersWalletFundwalletIndexRoute:
    UsersauthUsersWalletFundwalletIndexRoute,
}

const UsersauthUsersRouteRouteWithChildren =
  UsersauthUsersRouteRoute._addFileChildren(UsersauthUsersRouteRouteChildren)

interface UsersauthRouteRouteChildren {
  UsersauthAdsRouteRoute: typeof UsersauthAdsRouteRouteWithChildren
  UsersauthUsersRouteRoute: typeof UsersauthUsersRouteRouteWithChildren
}

const UsersauthRouteRouteChildren: UsersauthRouteRouteChildren = {
  UsersauthAdsRouteRoute: UsersauthAdsRouteRouteWithChildren,
  UsersauthUsersRouteRoute: UsersauthUsersRouteRouteWithChildren,
}

const UsersauthRouteRouteWithChildren = UsersauthRouteRoute._addFileChildren(
  UsersauthRouteRouteChildren,
)

interface PublicDarknavbarRouteRouteChildren {
  PublicDarknavbarDiscoveryIndexRoute: typeof PublicDarknavbarDiscoveryIndexRoute
}

const PublicDarknavbarRouteRouteChildren: PublicDarknavbarRouteRouteChildren = {
  PublicDarknavbarDiscoveryIndexRoute: PublicDarknavbarDiscoveryIndexRoute,
}

const PublicDarknavbarRouteRouteWithChildren =
  PublicDarknavbarRouteRoute._addFileChildren(
    PublicDarknavbarRouteRouteChildren,
  )

interface PublicLightnavbarRouteRouteChildren {
  PublicLightnavbarAboutIndexRoute: typeof PublicLightnavbarAboutIndexRoute
  PublicLightnavbarContactIndexRoute: typeof PublicLightnavbarContactIndexRoute
  PublicLightnavbarFaqsIndexRoute: typeof PublicLightnavbarFaqsIndexRoute
}

const PublicLightnavbarRouteRouteChildren: PublicLightnavbarRouteRouteChildren =
  {
    PublicLightnavbarAboutIndexRoute: PublicLightnavbarAboutIndexRoute,
    PublicLightnavbarContactIndexRoute: PublicLightnavbarContactIndexRoute,
    PublicLightnavbarFaqsIndexRoute: PublicLightnavbarFaqsIndexRoute,
  }

const PublicLightnavbarRouteRouteWithChildren =
  PublicLightnavbarRouteRoute._addFileChildren(
    PublicLightnavbarRouteRouteChildren,
  )

interface VendorsBillboardsRouteRouteChildren {
  VendorsBillboardsIndexRoute: typeof VendorsBillboardsIndexRoute
  VendorsBillboardsAddBillboardIndexRoute: typeof VendorsBillboardsAddBillboardIndexRoute
  VendorsBillboardsListingIndexRoute: typeof VendorsBillboardsListingIndexRoute
  VendorsBillboardsRequestsIndexRoute: typeof VendorsBillboardsRequestsIndexRoute
  VendorsBillboardsSettingsIndexRoute: typeof VendorsBillboardsSettingsIndexRoute
  VendorsBillboardsWalletIndexRoute: typeof VendorsBillboardsWalletIndexRoute
  VendorsBillboardsListingSlugIndexRoute: typeof VendorsBillboardsListingSlugIndexRoute
  VendorsBillboardsRequestsSlugIndexRoute: typeof VendorsBillboardsRequestsSlugIndexRoute
  VendorsBillboardsListingSlugEditIndexRoute: typeof VendorsBillboardsListingSlugEditIndexRoute
}

const VendorsBillboardsRouteRouteChildren: VendorsBillboardsRouteRouteChildren =
  {
    VendorsBillboardsIndexRoute: VendorsBillboardsIndexRoute,
    VendorsBillboardsAddBillboardIndexRoute:
      VendorsBillboardsAddBillboardIndexRoute,
    VendorsBillboardsListingIndexRoute: VendorsBillboardsListingIndexRoute,
    VendorsBillboardsRequestsIndexRoute: VendorsBillboardsRequestsIndexRoute,
    VendorsBillboardsSettingsIndexRoute: VendorsBillboardsSettingsIndexRoute,
    VendorsBillboardsWalletIndexRoute: VendorsBillboardsWalletIndexRoute,
    VendorsBillboardsListingSlugIndexRoute:
      VendorsBillboardsListingSlugIndexRoute,
    VendorsBillboardsRequestsSlugIndexRoute:
      VendorsBillboardsRequestsSlugIndexRoute,
    VendorsBillboardsListingSlugEditIndexRoute:
      VendorsBillboardsListingSlugEditIndexRoute,
  }

const VendorsBillboardsRouteRouteWithChildren =
  VendorsBillboardsRouteRoute._addFileChildren(
    VendorsBillboardsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersauthRouteRoute: UsersauthRouteRouteWithChildren,
  PublicDarknavbarRouteRoute: PublicDarknavbarRouteRouteWithChildren,
  PublicLightnavbarRouteRoute: PublicLightnavbarRouteRouteWithChildren,
  VendorsBillboardsRouteRoute: VendorsBillboardsRouteRouteWithChildren,
  AccessEmailVerificationIndexRoute: AccessEmailVerificationIndexRoute,
  AccessSigninIndexRoute: AccessSigninIndexRoute,
  AccessSignupIndexRoute: AccessSignupIndexRoute,
  VendorsInfluencersIndexRoute: VendorsInfluencersIndexRoute,
  AccessVendorsAcessLoginIndexRoute: AccessVendorsAcessLoginIndexRoute,
  AccessVendorsAcessOnboardingIndexRoute:
    AccessVendorsAcessOnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
